/// LibrePili: where a subtitle track came from.
///
/// Three tracks can sit in the same menu reading "中文" and mean very
/// different things: one the author wrote, one the platform's recogniser
/// produced, and one this device produced. They are not equally trustworthy
/// and the difference was invisible — a machine transcript looked exactly
/// like a human one.
///
/// Only the machine-made ones are annotated. An author's track is the
/// unremarkable case and carries no note: saying "作者提交" on most of the
/// list would add noise without adding information.
library;

enum SubtitleSource {
  /// Uploaded by whoever published the video. Often a translation rather
  /// than a transcript, which is why it cannot be used to tell what language
  /// is being spoken.
  author,

  /// Generated by the platform (YouTube's automatic captions, bilibili's
  /// `type == 1` tracks).
  platform,

  /// Generated here, by the on-device recogniser.
  device;

  /// The note shown beside the track name, or null where none is wanted.
  String? get label => switch (this) {
    SubtitleSource.author => null,
    SubtitleSource.platform => '平台生成',
    SubtitleSource.device => '端侧模型',
  };

  /// The track name with its note appended, for a one-line menu entry.
  String annotate(String name) => label == null ? name : '$name · $label';
}
