import 'package:PiliPlus/services/youtube/youtube.dart';
import 'package:flutter_test/flutter_test.dart';

import 'yt_test_support.dart';

void main() {
  group('YtVideoDetail from the RECORDED player response', () {
    late YtVideoDetail detail;

    setUp(
      () => detail = parseYtPlayerResponse(loadYtResponse(YtFixtures.playerOk)),
    );

    test('metadata', () {
      expect(detail.videoId, 'dQw4w9WgXcQ');
      expect(detail.title, contains('Never Gonna Give You Up'));
      expect(detail.author, 'Rick Astley');
      expect(detail.channelId, startsWith('UC'));
      expect(detail.duration, const Duration(seconds: 213));
      expect(detail.isLive, isFalse);
      expect(detail.viewCount, greaterThan(1000000));
      expect(detail.description, isNotEmpty);
    });

    test('expiry is read off streamingData', () {
      // Measured consistently 21540 s (~6 h).
      expect(detail.expiresIn.inSeconds, greaterThan(3600));
    });

    test('thumbnails parse and the largest is selectable', () {
      expect(detail.thumbnails, isNotEmpty);
      final best = detail.bestThumbnail!;
      expect(best.url, startsWith('https://'));
      for (final t in detail.thumbnails) {
        expect(
          (t.width ?? 0) * (t.height ?? 0),
          lessThanOrEqualTo((best.width ?? 0) * (best.height ?? 0)),
        );
      }
    });

    test('formats split into video and audio', () {
      expect(detail.formats, isNotEmpty);
      expect(detail.videoFormats, isNotEmpty);
      expect(detail.audioFormats, isNotEmpty);
      expect(
        detail.videoFormats.length + detail.audioFormats.length,
        detail.formats.length,
      );
    });

    test('caption tracks parse, including the auto-generated one', () {
      expect(detail.captionTracks, isNotEmpty);
      expect(detail.captionTracks.map((t) => t.languageCode), contains('en'));
      expect(detail.captionTracks.any((t) => t.isAutoGenerated), isTrue);
      final auto = detail.captionTracks.firstWhere((t) => t.isAutoGenerated);
      expect(auto.vssId, startsWith('a.'));
      final human = detail.captionTracks.firstWhere((t) => !t.isAutoGenerated);
      expect(human.vssId, isNot(startsWith('a.')));
    });
  });

  group('YtCaptionTrack.urlFor', () {
    test('appends the format and strips any existing fmt/tlang', () {
      const track = YtCaptionTrack(
        languageCode: 'en',
        baseUrl:
            'https://www.youtube.com/api/timedtext?v=x&lang=en'
            '&fmt=srv3&tlang=fr&sig=abc',
        vssId: '.en',
        name: 'English',
        translatable: true,
      );
      final url = track.urlFor(YtCaptionFormat.vtt);
      expect(url, isNot(contains('fmt=srv3')));
      expect(url, isNot(contains('tlang=fr')));
      expect(url, endsWith('&fmt=vtt'));
      expect(url, contains('sig=abc'));
    });

    test('auto-translation re-adds tlang after the format', () {
      const track = YtCaptionTrack(
        languageCode: 'en',
        baseUrl: 'https://www.youtube.com/api/timedtext?v=x&lang=en',
        vssId: '.en',
        name: 'English',
        translatable: true,
      );
      expect(
        track.urlFor(YtCaptionFormat.ttml, translateTo: 'de'),
        endsWith('&fmt=ttml&tlang=de'),
      );
    });

    test('a RECORDED track produces a well-formed url', () {
      final detail = parseYtPlayerResponse(loadYtResponse(YtFixtures.playerOk));
      final url = detail.captionTracks.first.urlFor(YtCaptionFormat.vtt);
      expect(url, startsWith('https://'));
      expect(url, endsWith('&fmt=vtt'));
    });
  });

  group('search results from the RECORDED response', () {
    late YtPage<YtSearchItem> page;

    setUp(() => page = parseSearchResults(loadYtFixture(YtFixtures.search)));

    test('items parse with ids, titles and authors', () {
      expect(page.items, isNotEmpty);
      for (final item in page.items) {
        expect(item.videoId, hasLength(11));
        expect(isYouTubeVideoId(item.videoId), isTrue);
        expect(item.title, isNotEmpty);
        expect(item.author, isNotEmpty);
      }
    });

    test('duration is parsed from the clock label', () {
      final withDuration = page.items.where((i) => i.duration != null);
      expect(withDuration, isNotEmpty);
      // The recorded first hit is a 5:16:54 course.
      expect(
        page.items.first.duration,
        const Duration(hours: 5, minutes: 16, seconds: 54),
      );
    });

    test('view counts and publish dates stay as the localised text', () {
      final first = page.items.first;
      expect(first.viewCountText, contains('views'));
      expect(first.publishedText, isNotNull);
    });

    test('channel ids come off the byline endpoint', () {
      expect(page.items.first.channelId, startsWith('UC'));
    });

    test('thumbnails parse', () {
      expect(page.items.first.thumbnails, isNotEmpty);
      expect(page.items.first.bestThumbnail!.url, startsWith('https://'));
    });

    test('a continuation token is found', () {
      expect(page.hasMore, isTrue);
      expect(page.continuation, isNotEmpty);
    });
  });

  group('related videos from the RECORDED next response', () {
    late Object? root;

    setUp(() => root = loadYtFixture(YtFixtures.next));

    // The shape change a fresh port misses: compactVideoRenderer is gone.
    test(
      'the fixture confirms lockupViewModel replaced compactVideoRenderer',
      () {
        expect(collectObjects(root, 'compactVideoRenderer'), isEmpty);
        expect(collectObjects(root, 'lockupViewModel'), isNotEmpty);
      },
    );

    test('related videos parse out of lockupViewModel', () {
      final related = parseRelatedVideos(root);
      expect(related, isNotEmpty);
      for (final item in related) {
        expect(isYouTubeVideoId(item.videoId), isTrue);
        expect(item.title, isNotEmpty);
      }
      expect(related.first.author, isNotEmpty);
      expect(related.first.duration, isNotNull);
      expect(related.first.thumbnails, isNotEmpty);
    });

    test('the legacy renderer is still read when present', () {
      final legacy = parseRelatedVideos({
        'contents': [
          {
            'compactVideoRenderer': {
              'videoId': 'dQw4w9WgXcQ',
              'title': {'simpleText': 'Legacy'},
              'longBylineText': {
                'runs': [
                  {
                    'text': 'Someone',
                    'navigationEndpoint': {
                      'browseEndpoint': {'browseId': 'UCabc'},
                    },
                  },
                ],
              },
              'lengthText': {'simpleText': '3:33'},
              'thumbnail': {
                'thumbnails': [
                  {'url': '//i.ytimg.com/x.jpg', 'width': 120, 'height': 90},
                ],
              },
            },
          },
        ],
      });
      expect(legacy, hasLength(1));
      expect(legacy.single.title, 'Legacy');
      expect(legacy.single.channelId, 'UCabc');
      expect(legacy.single.duration, const Duration(minutes: 3, seconds: 33));
      // Protocol-relative thumbnail URLs are made absolute.
      expect(legacy.single.thumbnails.single.url, startsWith('https://'));
    });

    test('the comments token is found by section identifier, not position', () {
      final token = parseCommentsContinuationToken(root);
      expect(token, isNotNull);
      expect(token, isNotEmpty);
      // The same tree carries other continuation tokens; the section lookup is
      // what tells them apart.
      expect(collectContinuationTokens(root), contains(token));
    });

    test('related() shaped access', () {
      final related = parseRelatedVideos(root);
      final bundle = YtRelatedAndComments(
        related,
        parseCommentsContinuationToken(root),
        parseVideoExtra(root),
      );
      expect(bundle.related, isNotEmpty);
      expect(bundle.commentsToken, isNotNull);
      expect(bundle.toString(), contains('comments=true'));
      // one response, three things: the shelf, the comments door, and the
      // metadata that used to cost a second request
      expect(bundle.extra.dateText, isNotNull);
    });
  });

  group('the watch page metadata in the RECORDED next response', () {
    late YtVideoExtra extra;

    setUp(() => extra = parseVideoExtra(loadYtFixture(YtFixtures.next)));

    test('the publish date is read, which the player response lacks', () {
      expect(extra.dateText, '25 Oct 2009');
      expect(extra.relativeDateText, '16 years ago');
    });

    test('the view count is the exact figure, not the abbreviated one', () {
      // the search results carry '1.8bn'; this is what the watch page shows
      expect(extra.viewCountText, '1,818,000,663 views');
    });

    test('the channel avatar and subscriber count come from here too', () {
      // this is what replaced a separate browse request made for the avatar
      expect(extra.ownerName, 'Rick Astley');
      expect(extra.subscriberText, '4.54m subscribers');
      expect(extra.ownerAvatar!.url, startsWith('https://'));
      expect(extra.isEmpty, isFalse);
    });

    test('a response without any of it reports empty rather than blanks', () {
      final none = parseVideoExtra(const {'contents': []});
      expect(none.isEmpty, isTrue);
      expect(none.dateText, isNull);
      expect(none.subscriberText, isNull);
    });
  });

  group('comments from the RECORDED continuation response', () {
    late YtPage<YtComment> page;
    late Object? root;

    setUp(() {
      root = loadYtFixture(YtFixtures.nextComments);
      page = parseComments(root);
    });

    test('the fixture is the entity-view-model form, not commentRenderer', () {
      expect(collectObjects(root, 'commentRenderer'), isEmpty);
      expect(collectObjects(root, 'commentEntityPayload'), isNotEmpty);
    });

    test('comments parse with author, content and counts', () {
      expect(page.items, isNotEmpty);
      for (final c in page.items) {
        expect(c.commentId, isNotEmpty);
        expect(c.author, isNotEmpty);
      }
      final first = page.items.first;
      expect(first.content, isNotEmpty);
      expect(first.authorChannelId, startsWith('UC'));
      expect(first.authorAvatar!.url, startsWith('https://'));
      expect(first.publishedText, isNotNull);
      expect(first.likeCountText, isNotNull);
    });

    test('the pinned flag comes from the joined commentViewModel', () {
      // The recorded page leads with the channel's pinned comment.
      expect(page.items.any((c) => c.isPinned), isTrue);
    });

    test(
      'the page continuation is the one NOT scoped to a comment thread',
      () {
        final token = page.continuation;
        expect(token, isNotNull);
        final threadTokens = {
          for (final t in collectObjects(root, 'commentThreadRenderer'))
            ...collectContinuationTokens(t),
        };
        expect(threadTokens, isNotEmpty, reason: 'reply tokens exist here');
        expect(
          threadTokens,
          isNot(contains(token)),
          reason: 'a reply token must never be served as the next page',
        );
      },
    );

    test('a thread with replies carries the token that loads them', () {
      final withReplies = page.items.where((c) => c.hasReplies).toList();
      expect(
        withReplies,
        isNotEmpty,
        reason: 'the recorded page has threads with replies',
      );
      final threadTokens = {
        for (final t in collectObjects(root, 'commentThreadRenderer'))
          ...collectContinuationTokens(t),
      };
      for (final c in withReplies) {
        // every reply token must be one of the thread-scoped ones, never the
        // page token — serving the page token here would silently reload the
        // whole comment list as if it were a thread
        expect(threadTokens, contains(c.replyToken));
        expect(c.replyToken, isNot(page.continuation));
      }
    });

    test('the token is paired with its own comment, not by position', () {
      // Two things this guards. First, a thread holds two commentViewModels
      // and the first one has no commentId at all, so "the first view model"
      // is not the comment. Second, this page carries 20 threads but only 6
      // comment payloads — the recording is trimmed — so a pairing done by
      // index across the two lists would be wrong for every one of them.
      final byId = {for (final c in page.items) c.commentId: c};
      var checked = 0;
      for (final thread in collectObjects(root, 'commentThreadRenderer')) {
        final tokens = collectContinuationTokens(thread);
        if (tokens.isEmpty) continue;
        for (final vm in collectObjects(thread, 'commentViewModel')) {
          if (vm['commentId'] case final String id when byId.containsKey(id)) {
            expect(byId[id]!.replyToken, tokens.first);
            checked++;
          }
        }
      }
      expect(checked, greaterThan(0), reason: 'nothing was actually paired');
    });

    test('a comment whose thread has no token has no replies', () {
      // Synthesised rather than read off the fixture: every thread there has
      // replies, so a fixture-driven version of this test would pass without
      // asserting anything.
      final parsed = parseComments({
        'contents': [
          {
            'commentThreadRenderer': {
              'commentViewModel': {
                'commentViewModel': {'commentId': 'no-replies'},
              },
            },
          },
        ],
        'frameworkUpdates': {
          'entityBatchUpdate': {
            'mutations': [
              {
                'payload': {
                  'commentEntityPayload': {
                    'properties': {
                      'commentId': 'no-replies',
                      'content': {'content': 'hi'},
                    },
                    'author': {'displayName': '@someone'},
                  },
                },
              },
            ],
          },
        },
      });
      expect(parsed.items.single.commentId, 'no-replies');
      expect(parsed.items.single.hasReplies, isFalse);
      expect(parsed.items.single.replyToken, isNull);
    });

    test('the legacy commentRenderer form is still read', () {
      final legacy = parseComments({
        'contents': [
          {
            'commentRenderer': {
              'commentId': 'abc',
              'authorText': {'simpleText': '@someone'},
              'contentText': {
                'runs': [
                  {'text': 'hello '},
                  {'text': 'world'},
                ],
              },
              'voteCount': {'simpleText': '12'},
              'publishedTimeText': {'simpleText': '2 days ago'},
              'authorIsChannelOwner': true,
              'pinnedCommentBadge': {'x': 1},
            },
          },
        ],
      });
      expect(legacy.items, hasLength(1));
      final c = legacy.items.single;
      expect(c.author, '@someone');
      expect(c.content, 'hello world');
      expect(c.likeCountText, '12');
      expect(c.authorIsUploader, isTrue);
      expect(c.isPinned, isTrue);
    });
  });

  group('json helpers', () {
    test('readText handles all four InnerTube text shapes', () {
      expect(readText('plain'), 'plain');
      expect(readText({'simpleText': 'simple'}), 'simple');
      expect(
        readText({
          'runs': [
            {'text': 'a'},
            {'text': 'b'},
          ],
        }),
        'ab',
      );
      expect(readText({'content': 'c'}), 'c');
      expect(readText(null), '');
      expect(readText(42), '');
    });

    test('asInt accepts int, double and string', () {
      expect(asInt(3), 3);
      expect(asInt(3.9), 3);
      expect(asInt('21540'), 21540);
      expect(asInt('3.9'), 3);
      expect(asInt('nope'), isNull);
      expect(asInt(null), isNull);
    });

    test('parseClockDuration', () {
      expect(parseClockDuration('13'), const Duration(seconds: 13));
      expect(
        parseClockDuration('4:13'),
        const Duration(minutes: 4, seconds: 13),
      );
      expect(
        parseClockDuration('1:02:30'),
        const Duration(hours: 1, minutes: 2, seconds: 30),
      );
      expect(parseClockDuration('LIVE'), isNull);
      expect(parseClockDuration('1:2:3:4'), isNull);
      expect(parseClockDuration(null), isNull);
    });

    test('collectByKey walks the whole tree in document order', () {
      final tree = {
        'a': {'k': 1},
        'b': [
          {'k': 2},
          {
            'c': {'k': 3},
          },
        ],
      };
      expect(collectByKey(tree, 'k'), [1, 2, 3]);
    });

    test('collectContinuationTokens de-duplicates', () {
      final tree = {
        'x': {
          'continuationCommand': {'token': 'T'},
        },
        'y': {
          'continuationCommand': {'token': 'T'},
        },
        'z': {
          'continuationCommand': {'token': 'U'},
        },
      };
      expect(collectContinuationTokens(tree), ['T', 'U']);
    });
  });
}
