name: Build for Windows x64

on:
  workflow_call:
    inputs:
      tag:
        description: "tag"
        required: false
        default: ""
        type: string
  workflow_dispatch:

jobs:
  build-windows-app:
    name: Release Windows x64
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Setup flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Set and Extract version
        shell: pwsh
        run: lib/scripts/build.ps1

      - name: Apply Patch
        shell: pwsh
        run: lib/scripts/patch.ps1 windows

      - name: Build Windows
        run: flutter build windows --release --dart-define-from-file=pili_release.json --no-pub

      - name: Prepare Upload
        run: |
          mkdir -p Release/LibrePili-Win
          mv build/windows/x64/runner/Release/* Release/LibrePili-Win/

      - name: Compress
        run: |
          Compress-Archive -Path "Release/LibrePili-Win" -DestinationPath "LibrePili_windows_${{env.version}}_x64_portable.zip"
        shell: pwsh

      - name: Release
        if: ${{ github.event.inputs.tag != '' }}
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.tag }}
          files: |
            LibrePili_windows_*.zip

      - name: Upload windows file release
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          archive: false
          name: Windows-file-x64-release
          path: LibrePili_windows_*.zip
